### ISSUE TITLE
Downloaded Mac OS arm64, installed app type: Intel

### ISSUE THREAD

**Issue by vladstudio** [drovp/drovp#4]
Hey! I used this link:

https://github.com/drovp/drovp/releases/latest/download/Drovp-arm64.dmg

and this is what I see.
![image](https://user-images.githubusercontent.com/914320/147502166-51605182-bb46-413f-9089-600855803d6d.png)

**Comment by tomasklaen** [comment]
Seeing #5 I guess you figured it out, so I'm gonna close this.
