### ISSUE TITLE
Error  installing "encode" plugin

### ISSUE THREAD

**Issue by vladstudio** [drovp/drovp#6]
![image](https://user-images.githubusercontent.com/914320/147502347-43692648-9ad2-4e3a-b938-c8f0daf823df.png)

Interestengly, the plugin seems to be installed after all.

**Comment by tomasklaen** [comment]
This happened to me once as well. I did some extraction code refactoring and it stopped so I assumed it's fixed. Using 7za on mac seems finicky. Will have to investigate further I guess.

In any case, if a dependency fails to install, you can always try again, or check the error in Extensions > Dependencies section.

**Comment by tomasklaen** [comment]
This should be fixed in 0.1.0. Report if it isn't and I'll reopen.
